
linters:
    disable-all: true
    enable:
        - wsl
        - thelper
        - tparallel
        - stylecheck
        - unconvert
        - reassign
        - predeclared
        - prealloc
        - nilerr
        - gci
        - errname
        - gofmt

    presets:
        - bugs
        - module
        - performance
        - unused

linters-settings:
    depguard:
        rules:
            main:
                allow:
                    - $gostd
                    - github.com/smoynes/elsie
